apiVersion: v1
kind: Namespace
metadata:
  name: interview-ns

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  namespace: interview-ns
  labels:
    db: postgres
data:
  POSTGRES_DB: predictx
  POSTGRES_USER: piuser
  PGDATA: /var/lib/postgresql/data/pgdata
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-db-pwd
  namespace: interview-ns
type: Opaque
data:
  POSTGRES_PASSWORD: U3ByaW5naXNuaWNl

---

apiVersion: apps/v1
kind: Deployment
metadata:
 name: postgresongke
 namespace: interview-ns
spec:
 strategy:
   rollingUpdate:
     maxSurge: 1
     maxUnavailable: 1
   type: RollingUpdate
 replicas: 1
 selector:
   matchLabels:
     db: postgres
 template:
   metadata:
     labels:
       db: postgres
   spec:
     containers:
       - name: postgres
         image: postgres:10
         resources:
           limits:
             cpu: "1"
             memory: "4Gi"
           requests:
             cpu: "1"
             memory: "4Gi"
         ports:
           - containerPort: 5432
         env:
           - name: POSTGRES_PASSWORD
             valueFrom:
               secretKeyRef:
                 name: postgres-db-pwd
                 key: POSTGRES_PASSWORD
         envFrom:
           - configMapRef:
               name: postgres-secret
         volumeMounts:
           - mountPath: /var/lib/postgresql/data
             name: postgredb
     volumes:
       - name: postgredb
         emptyDir: {}
---

apiVersion: v1
kind: Service
metadata:
  name: pg-service
  namespace: interview-ns
  labels:
    db: postgres
spec:
  type: NodePort
  selector:
    db: postgres
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 31115